bessctl up4 configuration is executed once
canonical/sdcore-upf-operator pull request #26
Opened 2023-08-14 16:32 UTC by gatici

# Description

Do not run bessctl up4 configuration twice in sdcore-upf-operator.
This patch creates a dummy file when bessctl configure is executed. So, bessctl configure command is executed once.
Fixing FileNotFoundError error while getting namespace through the file: "/var/run/secrets/kubernetes.io/serviceaccount/namespace" during the k8s service patcher creation.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2023-08-14 17:25 UTC, ghislainbourgeois requested changes
Small fixes to the test name, otherwise LGTM

2023-08-14 17:25 UTC, ghislainbourgeois commented on tests/unit/test_charm.py
> +    def test_given_can_connect_to_bessd_when_bessd_pebble_ready__bessctl_configure_is_executed(
```suggestion
    def test_given_can_connect_to_bessd_when_bessd_pebble_ready_then_bessctl_configure_is_executed(
```

2023-08-14 17:25 UTC, ghislainbourgeois commented on tests/unit/test_charm.py
> +    def test_bessd__pebble_ready__bessctl_executed_file_exists__bessctl_configure_not_executed(
```suggestion
    def test_given_can_connect_and_bessctl_executed_file_exists_then_bessctl_configure_not_executed(
```

2023-08-14 17:25 UTC, ghislainbourgeois commented on tests/unit/test_charm.py
> +    def test_bessd__pebble_ready__bessctl_executed_file_dont_exist__bessctl_configure_executed(
```suggestion
    def test_given_can_connect_and_bessctl_executed_file_dont_exist_then_bessctl_configure_executed(
```

2023-08-14 20:47 UTC, gatici commented on tests/unit/test_charm.py
> +    def test_given_can_connect_to_bessd_when_bessd_pebble_ready__bessctl_configure_is_executed(
Done

2023-08-14 20:47 UTC, gatici commented on tests/unit/test_charm.py
> +    def test_bessd__pebble_ready__bessctl_executed_file_exists__bessctl_configure_not_executed(
Done

2023-08-14 20:47 UTC, gatici commented on tests/unit/test_charm.py
> +    def test_bessd__pebble_ready__bessctl_executed_file_dont_exist__bessctl_configure_executed(
Done

2023-08-14 20:53 UTC, gatici commented
Ready to review again.

2023-08-15 18:53 UTC, ghislainbourgeois approved these changes

2023-08-16 08:37 UTC, gatici commented on src/charm.py
> +        except FileNotFoundError as e:
This error is happening everytime if we do not have that file "/var/run/secrets/kubernetes.io/serviceaccount/namespace". Hence, we usually get FileNotFoundError if microk8s is used in our environment. The error is not directly related with the unit tests. When we instantiate an instance from UPFOperatorCharm, object has a service_patcher using KubernetesServicePatch class. KubernetesServicePatch class has namespace property which looks for indicated file which causes FileNotFoundError in some environments. I think, patching KubernetesServicePatch class in observability_libs could be more stable solution.

2023-08-16 08:38 UTC, merged